<a href="https://colab.research.google.com/github/PRATEEK-RAJ-GUPTA/DEEP_LEARNING101/blob/main/linear_algebra_ragged_matrix_normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**tf.math.to_k-->Finds values and indices of the k largest entries for the last dimension.**

In [ ]:
import tensorflow as tf

In [ ]:
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
result.values.numpy()

array([99, 98, 96], dtype=int32)

**tf.linalg.matmul-->Multiplies matrix a by matrix b, producing a * b.**

In [ ]:
a=tf.constant([[1,2,0],
               [3,5,-1]])
b=tf.constant([[1,2,0,2],
               [3,5,-1,2],
               [4,5,6,0]])
tf.linalg.matmul(
    a,
    b,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[  7,  12,  -2,   6],
       [ 14,  26, -11,  16]], dtype=int32)>

In [ ]:
print(a@b)

tf.Tensor(
[[  7  12  -2   6]
 [ 14  26 -11  16]], shape=(2, 4), dtype=int32)


**TRANSPOSE**

In [ ]:
print(tf.transpose(a))

tf.Tensor(
[[ 1  3]
 [ 2  5]
 [ 0 -1]], shape=(3, 2), dtype=int32)


in 3-d matrix multiplication we are tend see the row and column of each dimensional matrix

In [ ]:
x_1=tf.constant([[[1,2],
                  [3,5]],
                  [[10,2],
                  [1,0]],
                  [[5,8],
                  [2,7]]])

x_2=tf.constant([[[5,1,4],
                  [34,15,1]],
                  [[1,2,2],
                  [5,3,2]],
                  [[2,2,3],
                  [1,1,1]]])


print(x_1)
print(x_2)

tf.Tensor(
[[[ 1  2]
  [ 3  5]]

 [[10  2]
  [ 1  0]]

 [[ 5  8]
  [ 2  7]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(
[[[ 5  1  4]
  [34 15  1]]

 [[ 1  2  2]
  [ 5  3  2]]

 [[ 2  2  3]
  [ 1  1  1]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tf.linalg.matmul(x_1,x_2))

tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 20  26  24]
  [  1   2   2]]

 [[ 18  18  23]
  [ 11  11  13]]], shape=(3, 2, 3), dtype=int32)


**matrix that are mostly zeros-->spase matix** tensorflow has method for it

**tf.linalg.cholesky-->Computes the Cholesky decomposition of one or more square matrices.**
tf.linalg.cholesky(
    input, name=None
)

**tf.linalg.cross(a,b,name=None)-->find the cross product of a and b**

**tf.linalg.det()-->return the determinant**

**tf.linalg.inv()**

**tf.linalg.matrix_transpose(a,name=matrix_transpose,conjugate=False**

**tf.linalg.svd--->compute the single value decomposition of one or more matrix**


# a is a tensor.
# s is a tensor of singular values.
# u is a tensor of left singular vectors.
# v is a tensor of right singular vectors.
s, u, v = svd(a)
s = svd(a, compute_uv=False)

**tf.einsum()-->it is basically and operator which provide us dynamic way to do matix operation**

In [ ]:
m0 = tf.random.normal(shape=[2, 3])
m1 = tf.random.normal(shape=[3, 5])
e = tf.einsum('ij,jk->ik', m0, m1)
# output[i,k] = sum_j m0[i,j] * m1[j, k]
print(e)

tf.Tensor(
[[-1.4922068   0.26155162  1.0182369   3.0723135   2.377229  ]
 [-0.19907314  0.33972892  0.25766155  1.7829735   2.1485343 ]], shape=(2, 5), dtype=float32)


dot product

In [ ]:
u = tf.random.normal(shape=[5])
v = tf.random.normal(shape=[5])
e = tf.einsum('i,i->', u, v)  # output = sum_i u[i]*v[i]
print(e.shape)

()


outer-product

In [ ]:
u = tf.random.normal(shape=[3])
v = tf.random.normal(shape=[5])
e = tf.einsum('i,j->ij', u, v)  # output[i,j] = u[i]*v[j]
print(e.shape)


(3, 5)


transpose

In [ ]:
m = tf.ones(2,3)
e = tf.einsum('ij->ji', m0)  # output[j,i] = m0[i,j]
print(e.shape)


(3, 2)


Batch-matrix multiplication-->3D MATRIX MULTIPLICATION

In [ ]:
s = tf.random.normal(shape=[7,5,3])
t = tf.random.normal(shape=[7,3,2])
e = tf.einsum('bij,bjk->bik', s, t)
# output[a,i,k] = sum_j s[a,i,j] * t[a, j, k]
print(e.shape)


(7, 5, 2)


**The matrix should have the same shape**
This method does not support broadcasting on named-axes. All axes with matching labels should have the same length. If you have length-1 axes, use tf.squeeze or tf.reshape to eliminate them.

To write code that is agnostic to the number of indices in the input use an ellipsis. The ellipsis is a placeholder for "whatever other indices fit here".

**TF.RAGGED**

This package defines ops for manipulating ragged tensors (tf.RaggedTensor), which are tensors with non-uniform shapes. In particular, each RaggedTensor has one or more ragged dimensions, which are dimensions whose slices may have different lengths. For example, the inner (column) dimension of rt=[[3, 1, 4, 1], [], [5, 9, 2], [6], []] is ragged, since the column slices (rt[0, :], ..., rt[4, :]) have different lengths. For a more detailed description of ragged tensors, see the tf.RaggedTensor class documentation and the Ragged Tensor Guide.

In [ ]:
tensor_two_d=[[1,2,0],
              [3,],
              [1,2,5,6,7,8,8],
              [2,3]]

tensor_ragged=tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[1, 2, 0], [3], [1, 2, 5, 6, 7, 8, 8], [2, 3]]>


**tf.ragged.boolean_mask-->Applies a boolean mask to data without flattening the mask dimensions.**

In [ ]:
T=True
F=False
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()

[[1, 3], [], [7]]

In [ ]:
tf.ragged.boolean_mask(  # Mask rows of a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([True, False, True])).to_list()

[[1, 2, 3], [5, 6]]

In [ ]:
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_lengths=[4, 0, 3, 1, 0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
print(tf.RaggedTensor.from_row_limits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_limits=[4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
dt = tf.constant([[5, 7, 0], [0, 3, 0], [6, 0, 0]])
tf.RaggedTensor.from_tensor(dt)

tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3])

<tf.RaggedTensor [[5], [], [6, 0, 0]]>

In [ ]:
print(tf.RaggedTensor.from_row_splits(
    values=[3, 1, 4, 1, 5, 9, 2, 6],
    row_splits=[0, 4, 4, 7, 8, 8]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Normalization

In [ ]:
normalizer=Normalization(axis=-1,mean=5,variance=4)#axis=-1 mean columns normalization
x_normalized=tf.constant([[3,4,5,6,7],
                         [4,5,6,7,8]])
normalizer(x_normalized)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-0.5,  0. ,  0.5,  1. ,  1.5]], dtype=float32)>

In [ ]:
normalizer=Normalization()
x_normalized=tf.constant([[3,4,5,6,7],
                         [4,5,6,7,8]])
normalizer.adapt(x_normalized)
normalizer(x_normalized)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-1., -1., -1., -1., -1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)>