<a href="https://colab.research.google.com/github/PRATEEK-RAJ-GUPTA/DEEP_LEARNING101/blob/main/REGRESSION_BACKWORDPROPAGATION_USING_CONVENTIONAL_AND_KERAS_METHOD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [6]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [7]:
#output calculation of the neuron
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [13]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    print("A"+str(l-1)+": ", A_prev)
    print("W"+str(l)+": ", Wl)
    print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    print("A"+str(l)+": ", A)
    print("**"*20)
          
  return A,A_prev

In [14]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************


In [18]:
y_hat=y_hat[0][0] # as we want the value of y_hat in number from 

In [20]:
A1

array([[1.6],
       [1.6]])

In [16]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [22]:
update_parameters(parameters,y,y_hat,A1,X)

In [23]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [26]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]


y_hat,A1 = L_layer_forward(X, parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
parameters



A0:  [[7]
 [9]]
W1:  [[0.11915588 0.1227486 ]
 [0.11916495 0.12276026]]
b1:  [[0.00261903]
 [0.00262033]]
----------------------------------------
A1:  [[1.90919473]
 [1.96670282]]
****************************************
A1:  [[1.90919473]
 [1.96670282]]
W2:  [[0.13605434]
 [0.13624384]]
b2:  [[0.14308282]]
----------------------------------------
A2:  [[0.67078818]]
****************************************


{'W1': array([[0.12840389, 0.1346389 ],
        [0.12845463, 0.13470413]]),
 'b1': array([[0.00394017],
        [0.00394742]]),
 'W2': array([[0.15258496],
        [0.15327238]]),
 'b2': array([[0.16193081]])}

In [27]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[2][0]


y_hat,A1 = L_layer_forward(X, parameters)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
parameters



A0:  [[ 6]
 [10]]
W1:  [[0.12840389 0.1346389 ]
 [0.12845463 0.13470413]]
b1:  [[0.00394017]
 [0.00394742]]
----------------------------------------
A1:  [[2.05890985]
 [2.15882217]]
****************************************
A1:  [[2.05890985]
 [2.15882217]]
W2:  [[0.15258496]
 [0.15327238]]
b2:  [[0.16193081]]
----------------------------------------
A2:  [[0.80697729]]
****************************************


{'W1': array([[0.13924499, 0.15270739],
        [0.13940323, 0.15295179]]),
 'b1': array([[0.00574702],
        [0.00577219]]),
 'W2': array([[0.17396889],
        [0.17569401]]),
 'b2': array([[0.18608005]])}

**ALL THE ABOVE CODE IN ONE FROM**

In [28]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************
A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.119136]]
----------------------------------------
A2:  [[0.50054357]]
****************************************
A0:  [[ 6]
 [10]]
W1:  [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1:  [[0.0019667]
 [0.0019667]]
----------------------------------------
A1:  [[1.83539945]
 [1.87200826]]
****************************************
A1:  [[1.83539945]
 [1.87200826]]
W2:  [[0.12712927]
 [0.127

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

**KERAS_IMPLEMENTATION**

In [29]:
import numpy as np
import pandas as pd

In [30]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [31]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [32]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [33]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.get_weights()

[array([[-1.1922103 ,  0.37163818],
        [-1.0006404 , -0.33132523]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.19012105],
        [-0.28804064]], dtype=float32),
 array([0.], dtype=float32)]

In [38]:
new_weight=[np.array([[0.1 , 0.1] , [0.1 , 0.1]],dtype=np.float32),
            np.array([0. , 0.],dtype=np.float32),
            np.array([[0.1],[0.1]],dtype=np.float32),
            np.array([0.],dtype=np.float32)]

In [40]:
model.set_weights(new_weight)

In [41]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [43]:
optimizer=keras.optimizers.Adam(learning_rate=.0001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [47]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=1000,verbose=1,batch_size=1)

Epoch 1/1000
4/4 [==============================] - 0s 8ms/step - loss: 2.2340
Epoch 2/1000
4/4 [==============================] - 0s 8ms/step - loss: 2.2217
Epoch 3/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.2140
Epoch 4/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.2004
Epoch 5/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.1876
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 2.1800
Epoch 7/1000
4/4 [==============================] - 0s 4ms/step - loss: 2.1668
Epoch 8/1000
4/4 [==============================] - 0s 4ms/step - loss: 2.1534
Epoch 9/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.1451
Epoch 10/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.1320
Epoch 11/1000
4/4 [==============================] - 0s 5ms/step - loss: 2.1268
Epoch 12/1000
4/4 [==============================] - 0s 5ms/step - loss: 2.1154
Epoch 13/1000
4/4 [==============================

In [48]:
model.get_weights()

[array([[0.34156576, 0.34156576],
        [0.4234657 , 0.4234657 ]], dtype=float32),
 array([0.29118127, 0.29118127], dtype=float32),
 array([[0.3986862],
        [0.3986862]], dtype=float32),
 array([0.22664094], dtype=float32)]