<a href="https://colab.research.google.com/github/PRATEEK-RAJ-GUPTA/DEEP_LEARNING101/blob/main/TENSOR_FUNCTIONALITY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensor are multidimensional array
ordered arrangement of number


In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d=tf.constant(2)#a tensor of 1-d having 2 as number
print(tensor_zero_d)

tf.Tensor(2, shape=(), dtype=int32)


In [3]:
tensor_one_d=tf.constant([2,0,-2])#a tensor of 1-d
print(tensor_one_d)

tf.Tensor([ 2  0 -2], shape=(3,), dtype=int32)


In [4]:
tensor_two_d=tf.constant([[2,0,-2],[1,1,1]])#a tensor of 1-d
print(tensor_two_d)

tf.Tensor(
[[ 2  0 -2]
 [ 1  1  1]], shape=(2, 3), dtype=int32)


In [5]:
tensor_three_d=tf.constant([[[2,0,-2],[1,1,1]],[[2,0,-2],[-1,-1,-1]],[[4,7,6],[9,6,2]]])#a tensor of 3-d
print(tensor_three_d)

tf.Tensor(
[[[ 2  0 -2]
  [ 1  1  1]]

 [[ 2  0 -2]
  [-1 -1 -1]]

 [[ 4  7  6]
  [ 9  6  2]]], shape=(3, 2, 3), dtype=int32)


bfloat32->leap from 32 to 16 bit very e

moving from float 64 to 32 or to 16

In [6]:
tensor_one_d=tf.constant([2,0.5,-2],dtype=tf.float32)
print(tensor_one_d)
casted_tensor_one_d=tf.cast(tensor_one_d,dtype=tf.float16)
print(casted_tensor_one_d)

tf.Tensor([ 2.   0.5 -2. ], shape=(3,), dtype=float32)
tf.Tensor([ 2.   0.5 -2. ], shape=(3,), dtype=float16)


PYTHON OBJECT INTO TENSOR

In [7]:
import numpy as np

In [8]:
x_np=np.array([2,3,4])
print(x_np)

[2 3 4]


In [9]:
x_tf=tf.convert_to_tensor(x_np,dtype=tf.float16)
print(x_tf)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float16)


TO CREATE n identity matrix-->tf.eye(
    num_rows,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)

In [10]:
identity_matrix=tf.eye(8,num_columns=3,batch_shape=[3])
print(identity_matrix)
#condition when row_number==column number

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(3, 8, 3), dtype=float32)


tf.fill-->Creates a tensor filled with a scalar value.
tf.fill(
    dims, value, name=None
)

In [11]:
tf.fill([4,3],9)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]], dtype=int32)>

tf.ones->all value set to one
i**t has a arument of datatype change whereas fill does** **not have** 

In [12]:
ones_tensor=tf.ones([4,4])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [13]:
zeros_tensor=tf.zeros([2,4,4])
print(zeros_tensor)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 4, 4), dtype=float32)


**tf.ones_like**
Creates a tensor of all ones that has the same shape as the input.






tf.ones_like(
    input, dtype=None, name=None
)

In [14]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [15]:
tf.randon_normal_initializer

AttributeError: ignored

**tf.randon_normal_initializer->Initializer that generates tensors with a normal distribution. tf.random_normal_initializer( mean=0.0, stddev=0.05, seed=None )**

In [17]:
normal_tensor=tf.random_normal_initializer(mean=0,stddev=0.05,seed=None)

In [18]:
print(normal_tensor)

tf.range-->Creates a sequence of numbers.
tf.range(limit, delta=1, dtype=None, name='range')
tf.range(start, limit, delta=1, dtype=None, name='range') 

**tf.range-->Creates a sequence of numbers.
tf.range(limit, delta=1, dtype=None, name='range')
tf.range(start, limit, delta=1, dtype=None, name='range') **

In [19]:
start = 3
limit = 18
delta = 3
rnage_tensor=tf.range(start, limit, delta)
print(rnage_tensor)
# start to limit-1


tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)


**tf.shape->give the shape**
it return a list but the function .shape return a tuple

In [20]:
print(tf.shape(tensor_three_d))

tf.Tensor([3 2 3], shape=(3,), dtype=int32)


tf.size-->no of element in tensor

**tf.random_generator**

In [21]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.622292  ,  0.12794739, -0.9379128 ],
       [-0.3565745 ,  1.18828   ,  0.6665595 ]], dtype=float32)>

In [22]:
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.9830542 , -0.985812  , -1.8495023 ],
       [-0.6278928 ,  1.132487  , -0.78076917]], dtype=float32)>

**in non-deterministic way we are generating diffferent random everytime but with seed we will not**

In [23]:
g = tf.random.Generator.from_seed(1234)
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.9356609 ,  1.0854305 , -0.93788373],
       [-0.5061547 ,  1.3169702 ,  0.7137579 ]], dtype=float32)>

In [24]:
g.normal(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.39647493,  0.83695656, -0.30946946],
       [ 1.1206646 ,  1.008526  , -0.10185789]], dtype=float32)>

In [25]:
g = tf.random.Generator.from_seed(1234)
g.normal(shape=(2, 3),mean=100,stddev=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[100.93566 , 101.085434,  99.06212 ],
       [ 99.49384 , 101.31697 , 100.71376 ]], dtype=float32)>

In [26]:
g = tf.random.Generator.from_seed(1234)
g.normal(shape=(2, 3),mean=100,stddev=100)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[193.5661  , 208.54306 ,   6.211624],
       [ 49.38453 , 231.69702 , 171.3758  ]], dtype=float32)>

**value to be between ninval and maxval**

In [27]:
g = tf.random.Generator.from_seed(1234)
g.uniform(shape=(2, 3),minval=0,maxval=100)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[35.81475 , 11.322761, 56.670906],
       [67.12369 , 32.565056, 17.095459]], dtype=float32)>

In [28]:
g = tf.random.Generator.from_seed(1234)
g.uniform(shape=(2, 3),minval=0,maxval=1000)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[358.1475 , 113.22761, 566.70905],
       [671.2369 , 325.65057, 170.95459]], dtype=float32)>

**tf.random.normal(shape,mean,stddev,dtype,seed,name)**

In [29]:
tf.random.normal((3,4),mean=0,stddev=1.0,dtype=tf.dtypes.float32,seed=None,name="Random Number with Normal Distribution")

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.53508705, -0.5796262 ,  1.3805901 ,  0.06075319],
       [ 0.22476332,  0.97427255,  1.8780966 ,  1.1366665 ],
       [-0.272392  , -1.259044  , -0.53289926,  0.98424023]],
      dtype=float32)>

In [30]:
tf.random.uniform((3,4),minval=0,maxval=1.0,dtype=tf.dtypes.float32,seed=None,name="Random Number with Normal Distribution")

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.34279144, 0.06602979, 0.8540745 , 0.41591442],
       [0.7832916 , 0.3654971 , 0.80264235, 0.12592292],
       [0.36132216, 0.7407553 , 0.9026619 , 0.61293244]], dtype=float32)>

**tensor_index**
MIN:MAX-1

In [31]:
tensor_indexed=tf.constant([3,6,2,4,6,66,7],dtype=tf.float32)
print(tensor_indexed)
print(tensor_indexed[0:4])

tf.Tensor([ 3.  6.  2.  4.  6. 66.  7.], shape=(7,), dtype=float32)
tf.Tensor([3. 6. 2. 4.], shape=(4,), dtype=float32)


In [33]:
tensor_two_d=tf.constant([[1,2,0],
                          [3,5,-1],
                          [1,5,6],
                          [2,3,8]])
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)


[ROW PART,COLUMN PART]

In [34]:
print(tensor_two_d[0:3,])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [35]:
print(tensor_two_d[2,])

tf.Tensor([1 5 6], shape=(3,), dtype=int32)


In [36]:
print(tensor_two_d[2,1:])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [42]:
print(tensor_two_d[1:3,0])

tf.Tensor([3 1], shape=(2,), dtype=int32)


In [43]:
print(tensor_two_d[...,0:2]) # three dot means everything

tf.Tensor(
[[1 2]
 [3 5]
 [1 5]
 [2 3]], shape=(4, 2), dtype=int32)


In [45]:
tensor_three_d=tf.constant([[[1,2,0],
                             [3,5,-1]],
                            
                            [[10,2,0],
                             [1,0,2]],
                            
                            [[5,8,0],
                             [2,7,0]],

                             [[2,1,9],
                              [4,-3,32]]])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


**['FIRST_DIM','SECOND_DIM','THIRD_DIM']**

In [47]:
print(tensor_three_d[0,0,:])

tf.Tensor([1 2 0], shape=(3,), dtype=int32)


In [48]:
print(tensor_three_d[0,:,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [49]:
print(tensor_three_d[0,:,-1])

tf.Tensor([ 0 -1], shape=(2,), dtype=int32)


In [51]:
print(tensor_three_d[0:2,:,:])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]], shape=(2, 2, 3), dtype=int32)


In [52]:
print(tensor_three_d[...,:,2])

tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


**MATH FUNCTIONALITY**

In [53]:
x_abs=tf.constant([-2.25,3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

in case of complex number ghe output value is root-over(a2 +b2)

In [54]:
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)


<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [55]:
tf.sqrt((-2.25**2 + 4.75**2))

<tf.Tensor: shape=(), dtype=float32, numpy=4.1833>

In [56]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.add(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10], dtype=int32)>

In [57]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.multiply(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25], dtype=int32)>

In [60]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.subtract(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 0, 0, 0], dtype=int32)>

In [61]:
x = [1, 2, 3, 4, 5]
y = tf.constant([1, 2, 3, 4, 5])
tf.divide(x, y)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 1., 1., 1., 1.])>

when there is a division from zero we will get error so we use method math.divide.nan which will give the anser as 0

In [63]:
x = tf.constant([1, 2, 3, 4, 5],dtype=tf.float32)
y = tf.constant([1, 2, 3, 0, 5],dtype=tf.float32)
print(tf.math.divide_no_nan(x,y))

tf.Tensor([1. 1. 1. 0. 1.], shape=(5,), dtype=float32)


In [66]:
x = tf.constant([1, 2, 3, 4, 5],dtype=tf.float32)
y = tf.constant([7],dtype=tf.float32)
#example of bradcasting  where a smaller tensor is stretched out as [7,7,7,7,7]
print(tf.add(x,y))

tf.Tensor([ 8.  9. 10. 11. 12.], shape=(5,), dtype=float32)


**MATRIX MULTIPLICATION**

In [67]:
x_1=tf.constant([[5,3,6,6,4,6],],dtype=tf.float32)
y_1=tf.constant([[5],[7],[6]],dtype=tf.float32)

print(tf.math.multiply(x_1,y_1))

tf.Tensor(
[[25. 15. 30. 30. 20. 30.]
 [35. 21. 42. 42. 28. 42.]
 [30. 18. 36. 36. 24. 36.]], shape=(3, 6), dtype=float32)


**tf.matm.argmax-->give the position of the maximum value**

In [68]:
x_argmax=tf.constant([[2,20,30,3,6],
                      [3,11,16,1,8],
                      [14,45,23,5,27]])

print(tf.math.argmin(x_argmax,0))# here 0 is saying the comparision is done o nthe basis of the column

tf.Tensor([0 1 1 1 0], shape=(5,), dtype=int64)


**in the above code the column are compared like for example 2,3,14 are comapared and the index of the highest position is returned**
if the axis 1 than row wise is compared 
2,20.30,3,6

**tf.pow-->Given a tensor x and a tensor y, this operation computes 
 for corresponding elements in x and y. For example:**

In [69]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

**tf.math.reduce_sum-->Computes the sum of elements across dimensions of a tensor.**
so basicilallyb if axis is not specified we goes on adding the number


In [71]:
x = tf.constant([[1, 1, 1], [1, 1, 1]]) 
x.numpy()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [72]:
tf.reduce_sum(x).numpy()

6

In [73]:
tensor_two_d=tf.constant([[2,0,-2],[1,1,1]])#a tensor of 2-d

print(tf.math.reduce_sum(tensor_two_d,axis=0,keepdims=False,name=None))


tf.Tensor([ 3  1 -1], shape=(3,), dtype=int32)


if axis =0 we are suming the column wise
if the axis=1 we are summing row wise

In [74]:
tensor_two_d=tf.constant([[2,0,-2],[1,1,1]])#a tensor of 2-d

print(tf.math.reduce_max(tensor_two_d,axis=0,keepdims=False,name=None))


tf.Tensor([2 1 1], shape=(3,), dtype=int32)


In [75]:
tensor_two_d=tf.constant([[2,0,-2],[1,1,1]])#a tensor of 2-d

print(tf.math.reduce_mean(tensor_two_d,axis=0,keepdims=False,name=None))


tf.Tensor([1 0 0], shape=(3,), dtype=int32)


tf.math.sigmoid(
    x, name=None
)

In [76]:
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5      , 0.7310586, 1.       , 1.       ], dtype=float32)>

**tf.top_k**